### ISSUE TITLE
Tip: Atualizar o README.md

### ISSUE THREAD

**Issue by dannRocha** [JulioEvencio/jogo_da_velha#1]
Ei @JulioEvencio, coloca um gif ou um print( screenshot ) do jogo rodando no REAME.md, fica mais fácil saber o q vc criou sem executar o código.

<p>
    <img src="https://media.giphy.com/media/3o6Ygq8LzuNBlGkRNK/giphy.gif" alt="gif demo"/>
</p>

**Comment by JulioEvencio** [comment]
Vou tentar colocar essa aqui:
![Captura de Tela (42)](https://user-images.githubusercontent.com/65574850/89823912-a4e70600-db28-11ea-90a3-4c21dc562fd6.png)

**Comment by JulioEvencio** [comment]
> Ei @JulioEvencio, coloca um gif ou um print( screenshot ) do jogo rodando no REAME.md, fica mais fácil saber o q vc criou sem executar o código.
> 
> ![gif demo](https://camo.githubusercontent.com/9c88c7178d0d222beb5792367c7059d0b97fb885/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f36596771384c7a754e426c476b524e4b2f67697068792e676966)

Acabei de adicionar, Obrigado pela dica!! 👍

**Comment by dannRocha** [comment]
OK
